apiVersion: v2
name: garm
description: GARM (Github/Gitea Actions Runner Manager) Helm Chart
icon: "https://raw.githubusercontent.com/cloudbase/garm/refs/heads/main/doc/ima\
  ges/garm-dark.svg"
sources:
  - https://github.com/igrikus/garm-helm-chart
  - https://github.com/cloudbase/garm
type: application
version: 4.0.0
appVersion: "v0.2.0"
