---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - garm.igrikus.dev
  resources:
  - enterprises
  - giteacredentials
  - giteaendpoints
  - giteaorganizations
  - githubcredentials
  - githubendpoints
  - pools
  - repositories
  - runners
  - runnertemplates
  - serversettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - garm.igrikus.dev
  resources:
  - enterprises/finalizers
  - giteacredentials/finalizers
  - giteaendpoints/finalizers
  - giteaorganizations/finalizers
  - githubcredentials/finalizers
  - githubendpoints/finalizers
  - pools/finalizers
  - repositories/finalizers
  - runners/finalizers
  - runnertemplates/finalizers
  verbs:
  - update
- apiGroups:
  - garm.igrikus.dev
  resources:
  - enterprises/status
  - giteacredentials/status
  - giteaendpoints/status
  - giteaorganizations/status
  - githubcredentials/status
  - githubendpoints/status
  - pools/status
  - repositories/status
  - runners/status
  - runnertemplates/status
  - serversettings/status
  verbs:
  - get
  - patch
  - update
