{{- if .Values.runnerTemplates }}
{{- range .Values.runnerTemplates }}
{{- if not .content }}
{{- fail (printf "runnerTemplate %q is missing a 'content' attribute." .name) }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "garm.fullname" $ }}-template-content-{{ .name }}"
  labels:
    {{- include "garm.labels" $ | nindent 4 }}
data:
  template: |-
{{ .content | indent 4 }}
{{- end }}
{{- end }}
