apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "garm.fullname" . }}-init-profile-script"
  labels:
    {{- include "garm.labels" . | nindent 4 }}
data:
  init-profile.sh: |-
    #!/bin/sh
    set -e
    echo "Creating garm-cli profile..."
    # This container runs every time the operator pod starts, ensuring the CLI profile is always present.
    # The profile is stored on an emptyDir volume, so it does not persist across pod restarts.
    garm-cli profile add \
      --name "{{ include "garm.fullname" . }}" \
      --url "http://{{ include "garm.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}" \
      --username "$GARM_ADMIN_USERNAME" \
      --password "$GARM_ADMIN_PASSWORD"
