apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "garm.fullname" . }}-init-organizations-script"
  labels:
    {{- include "garm.labels" . | nindent 4 }}
data:
  init-organizations.sh: |-
    #!/bin/sh
    set -e
    echo "Configuring GARM organizations"
    

    {{- if .Values.forges.gitea.organizations }}
    {{- range .Values.forges.gitea.organizations }}
    ORG_NAME="{{ .name }}"
    if ! garm-cli organization list | grep -wq "${ORG_NAME}"; then
      echo "Creating organization ${ORG_NAME}"
      garm-cli organization add --forge-type gitea --name "{{ .name }}" --credentials "{{ .credName }}" --install-webhook --random-webhook-secret
    else
      echo "Organization ${ORG_NAME} already exists."
    fi
    {{- end }}
    {{- end }}

    
