apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "garm.fullname" . }}-init-credentials-script"
  labels:
    {{- include "garm.labels" . | nindent 4 }}
data:
  init-credentials.sh: |-
    #!/bin/sh
    set -e
    echo "Configuring GARM credentials"
    

    {{- if .Values.forges.gitea }}
    {{- if .Values.forges.gitea.credentials }}
    {{- range $i, $cred := .Values.forges.gitea.credentials }}
    GITEA_URL=$(cat /gitea-secrets/{{ $cred.name }}/{{ $cred.baseUrlKey }})
    {{- if $cred.apiUrlKey }}
    GITEA_API_URL=$(cat /gitea-secrets/{{ $cred.name }}/{{ $cred.apiUrlKey }})
    {{- else }}
    GITEA_API_URL="$GITEA_URL"
    {{- end }}
    GITEA_TOKEN=$(cat /gitea-secrets/{{ $cred.name }}/{{ $cred.tokenKey }})

    ENDPOINT_NAME="{{ $cred.name }}"
    if ! garm-cli gitea endpoint list | grep -wq "${ENDPOINT_NAME}"; then
      echo "Creating Gitea endpoint ${ENDPOINT_NAME}"
      garm-cli gitea endpoint create --api-base-url "$GITEA_API_URL" --base-url "$GITEA_URL" --description "{{ $cred.name }}" --name "{{ $cred.name }}"
    else
      echo "Gitea endpoint ${ENDPOINT_NAME} already exists."
    fi

    CRED_NAME="{{ $cred.name }}"
    if ! garm-cli gitea credentials list | grep -wq "${CRED_NAME}"; then
      echo "Creating Gitea credentials ${CRED_NAME}"
      garm-cli gitea credentials add --endpoint "{{ $cred.name }}" --auth-type pat --pat-oauth-token "$GITEA_TOKEN" --name "$CRED_NAME" --description "$CRED_NAME access token"
    else
      echo "Gitea credentials ${CRED_NAME} already exists."
    fi
    {{- end }}
    {{- end }}
    {{- end }}

    {{- if .Values.forges.github.credentials }}
    {{- range $cred := .Values.forges.github.credentials }}
      {{- if $cred.urlKey }}
      ENDPOINT_NAME="{{ $cred.name }}"
      if ! garm-cli github endpoint list | grep -wq "${ENDPOINT_NAME}"; then
        echo "Creating GitHub endpoint ${ENDPOINT_NAME}"
        GITHUB_URL=$(cat /github-secrets/{{ $cred.name }}/{{ $cred.urlKey }})
        garm-cli github endpoint create \
          --api-base-url "$GITHUB_URL" \
          --base-url "$GITHUB_URL" \
          --description "{{ $cred.name }}" \
          --name "{{ $cred.name }}"
      else
        echo "GitHub endpoint ${ENDPOINT_NAME} already exists."
      fi
      {{- end }}

      CRED_NAME="{{ $cred.name }}"
      # The check for github credentials is more complex due to auth types
      # For now, we assume we can re-run the add command safely or skip the check.
      echo "Creating GitHub credentials ${CRED_NAME}"
      {{- if eq $cred.authType "pat" }}
      GITHUB_TOKEN=$(cat /github-secrets/{{ $cred.name }}/{{ $cred.tokenKey }})
      garm-cli github credentials add \
        --name "{{ $cred.name }}"
        {{- if $cred.urlKey }}
        --endpoint "{{ $cred.name }}" \
        {{- end }}
        --auth-type pat \
        --pat-oauth-token "$GITHUB_TOKEN"
      {{- else if eq $cred.authType "app" }}
      APP_ID=$(cat /github-secrets/{{ $cred.name }}/{{ $cred.appIdKey }})
      INSTALL_ID=$(cat /github-secrets/{{ $cred.name }}/{{ $cred.appInstallationIdKey }})
      PRIVATE_KEY_PATH="/github-secrets/{{ $cred.name }}/{{ $cred.privateKeyKey }}"
      garm-cli github credentials add \
        --name "{{ $cred.name }}"
        {{- if $cred.urlKey }}
        --endpoint "{{ $cred.name }}" \
        {{- end }}
        --auth-type app \
        --app-id "$APP_ID" \
        --app-installation-id "$INSTALL_ID" \
        --private-key-path "$PRIVATE_KEY_PATH"
      {{- end }}
    {{- end }}
    {{- end }}

    
