{{- if .Values.operator.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "garm.controllerName" . }}
  labels:
    {{- include "garm.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "garm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.operator.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "garm.labels" . | nindent 8 }}
        app.kubernetes.io/component: controller
        {{- with .Values.operator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "garm.controllerServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.operator.securityContext | nindent 8 }}
      containers:
        - name: manager
          image: "{{ .Values.operator.image.repository }}:{{ default .Chart.Version .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            {{- if .Values.operator.leaderElection }}
            - --leader-elect
            {{- end }}
            - --health-probe-bind-address=:8081
          env:
            - name: GARM_BASE_URL
              value: {{ .Values.operator.garmBaseUrl | default (printf "%s://%s:%v" (ternary "https" "http" .Values.garm.tls.enabled) (include "garm.fullname" .) .Values.service.port) | quote }}
            - name: GARM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "garm.admin-secret-name" . }}
                  key: {{ .Values.garm.admin.usernameKey }}
            - name: GARM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "garm.admin-secret-name" . }}
                  key: {{ .Values.garm.admin.passwordKey }}
          securityContext:
            {{- toYaml .Values.operator.containerSecurityContext | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.resources.operator }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
