apiVersion: garm.igrikus.dev/v1alpha1
kind: Enterprise
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: enterprise-sample
spec:
  # TODO(user): Add fields here
