apiVersion: garm.igrikus.dev/v1alpha1
kind: GithubCredentials
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: githubcredentials-sample
spec:
  # TODO(user): Add fields here
