## Append samples of your project ##
resources:
- garm_v1alpha1_giteaendpoint.yaml
- garm_v1alpha1_githubendpoint.yaml
- garm_v1alpha1_giteacredentials.yaml
- garm_v1alpha1_githubcredentials.yaml
- garm_v1alpha1_giteaorganization.yaml
- garm_v1alpha1_repository.yaml
- garm_v1alpha1_enterprise.yaml
- garm_v1alpha1_runnertemplate.yaml
- garm_v1alpha1_pool.yaml
- garm_v1alpha1_runner.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
